topnav_title: Mute Vol 1, No. 0 − Can Art Survive the 20th Century? 1994 Nov, ISSN 1356-7748-01
# this appears on the top navigation bar next to the home button

site_title: Mute Vol 1, No. 0 − Can Art Survive the 20th Century? 1994 Nov, ISSN 1356-7748-01
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
